[package]
name = "proyecto_cubos"
version = "0.1.0"
edition = "2024"
default-run = "proyecto_cubos"

[profile.dev]
opt-level = 3
debug = false

[dependencies]
nalgebra-glm = "0.20.0"
rand = "0.9.2"
raylib = "5.5.1"
rayon = "1.8"
image = "0.24"
